export const XP_AWARDS = {
  TASK_COMPLETED: 10,
  FAST_TASK_BONUS: 5,
  X402_PAYMENT_RECEIVED: 20,
  SUBSCRIPTION_ACQUIRED: 50,
  ZK_PASSPORT_MINTED: 100,
  UPTIME_24H_NO_ERRORS: 30,
  QUEST_COMPLETED: 200,
} as const

export const AGENT_LEVEL_CAP = 50
export const FIRST_LEVEL_XP_THRESHOLD = 100
export const LEVEL_XP_MULTIPLIER = 1.5
export const FAST_TASK_MAX_DURATION_MS = 30_000
